repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.26.0
  hooks:
    - id: terraform_fmt
    - id: terraform_docs_without_aggregate_type_defaults
      args: ['--args=--sort-inputs-by-required']
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
    - id: check-merge-conflict